### ISSUE TITLE
A little clarification

### ISSUE THREAD

**Issue by devSarry** [cklmercer/vue-feathers-client#1]
You think you could explain a bit what the router folder is doing? I've looked through the vue-router docs but I don't see any mention of adding a controller to it.  What kind of stuff can be put into it?

**Comment by cklmercer** [comment]
Sorry about the confusion.. the "controllers" are just arrays. We're just
using the `...` operator to essentially merge their contents into a larger
array.

**Comment by devSarry** [comment]
OK what about when trying to use single file components
I'm getting this error can you make anything of it?
```bash
ERROR in ./~/buble-loader?{"objectAssign":"Object.assign"}!./~/vue-loader/lib/selector.js?type=script&index=0!./app/components/App.vue
Module not found: Error: Can't resolve '.nav.vue' in '/home/vagrant/Code/feathers/vue-demo/app/components'
 @ ./~/buble-loader?{"objectAssign":"Object.assign"}!./~/vue-loader/lib/selector.js?type=script&index=0!./app/components/App.vue 61:18-37
 @ ./app/components/App.vue
 @ ./app/index.js
```

**Comment by cklmercer** [comment]
Looks like you might have a typo.. Do you mean to include the leading `.` here?
```
 Error: Can't resolve '.nav.vue'
```

The root component `app.vue` is a single file component, so I don't think that's the issue.. Something could've broken.. I'm going to be revisiting this package very soon. I'll double check everything then.

**Comment by dopyoman** [comment]
I don't think it's a typo i've been testing it out for a few days now with several different builds. I might be implementing routing wrong since the error only happens when I try and use the `<route-link>` component.

I'll upload a sample repo if you want to take a look.
